# To run tests for a specific Node.js version, use:
#   docker compose up node12
# To build without using the cache, run:
#   docker compose build --no-cache node12
# Then start the service:
#   docker compose up node12
# Replace 'node12' with the desired service (node12, node14, node16, node18, node20, node22)
#
# To run tests for all Node.js versions in parallel, use:
#   docker compose up

services:
  # Node.js 12 through 22 test runners
  node12:
    build:
      context: .
      target: node12
    working_dir: /workspace
    entrypoint: /workspace/docker.entrypoint.sh
    volumes:
      - ./bin:/workspace/bin
      - ./docker.entrypoint.sh:/workspace/docker.entrypoint.sh
      - ./eslint.config.mjs:/workspace/eslint.config.mjs
      - ./gulpfile.js:/workspace/gulpfile.js
      - ./index-builder.js:/workspace/index-builder.js
      - ./jest.config.ts:/workspace/jest.config.ts
      - ./lint-staged.config.js:/workspace/lint-staged.config.js
      - ./package.json:/workspace/package.json
      - ./packer.js:/workspace/packer.js
      - ./prettierrc.json:/workspace/.prettierrc.json
      - ./rollup.config.js:/workspace/rollup.config.js
      - ./src:/workspace/src
      - ./test:/workspace/test
      - ./tmp/.deploy_git:/workspace/tmp/.deploy_git
      - ./tmp/docker-caches/node-12/dist:/workspace/dist
      - ./tmp/docker-caches/node-12/logs:/workspace/tmp/logs
      - ./tmp/docker-caches/node-12/tmp/jest:/workspace/tmp/jest
      - ./tmp/project-test:/workspace/tmp/project-test
      - ./tsconfig.base.json:/workspace/tsconfig.base.json
      - ./tsconfig.build.json:/workspace/tsconfig.build.json
      - ./tsconfig.jest.json:/workspace/tsconfig.jest.json
      - ./tsconfig.json:/workspace/tsconfig.json
  node14:
    build:
      context: .
      target: node14
    working_dir: /workspace
    entrypoint: /workspace/docker.entrypoint.sh
    volumes:
      - ./bin:/workspace/bin
      - ./docker.entrypoint.sh:/workspace/docker.entrypoint.sh
      - ./eslint.config.mjs:/workspace/eslint.config.mjs
      - ./gulpfile.js:/workspace/gulpfile.js
      - ./index-builder.js:/workspace/index-builder.js
      - ./jest.config.ts:/workspace/jest.config.ts
      - ./lint-staged.config.js:/workspace/lint-staged.config.js
      - ./package.json:/workspace/package.json
      - ./packer.js:/workspace/packer.js
      - ./prettierrc.json:/workspace/.prettierrc.json
      - ./rollup.config.js:/workspace/rollup.config.js
      - ./src:/workspace/src
      - ./test:/workspace/test
      - ./tmp/.deploy_git:/workspace/tmp/.deploy_git
      - ./tmp/docker-caches/node-14/dist:/workspace/dist
      - ./tmp/docker-caches/node-14/logs:/workspace/tmp/logs
      - ./tmp/docker-caches/node-14/tmp/jest:/workspace/tmp/jest
      - ./tmp/project-test:/workspace/tmp/project-test
      - ./tsconfig.base.json:/workspace/tsconfig.base.json
      - ./tsconfig.build.json:/workspace/tsconfig.build.json
      - ./tsconfig.jest.json:/workspace/tsconfig.jest.json
      - ./tsconfig.json:/workspace/tsconfig.json
  node16:
    build:
      context: .
      target: node16
    working_dir: /workspace
    entrypoint: /workspace/docker.entrypoint.sh
    volumes:
      - ./bin:/workspace/bin
      - ./docker.entrypoint.sh:/workspace/docker.entrypoint.sh
      - ./eslint.config.mjs:/workspace/eslint.config.mjs
      - ./gulpfile.js:/workspace/gulpfile.js
      - ./index-builder.js:/workspace/index-builder.js
      - ./jest.config.ts:/workspace/jest.config.ts
      - ./lint-staged.config.js:/workspace/lint-staged.config.js
      - ./package.json:/workspace/package.json
      - ./packer.js:/workspace/packer.js
      - ./prettierrc.json:/workspace/.prettierrc.json
      - ./rollup.config.js:/workspace/rollup.config.js
      - ./src:/workspace/src
      - ./test:/workspace/test
      - ./tmp/.deploy_git:/workspace/tmp/.deploy_git
      - ./tmp/docker-caches/node-16/dist:/workspace/dist
      - ./tmp/docker-caches/node-16/logs:/workspace/tmp/logs
      - ./tmp/docker-caches/node-16/tmp/jest:/workspace/tmp/jest
      - ./tmp/project-test:/workspace/tmp/project-test
      - ./tsconfig.base.json:/workspace/tsconfig.base.json
      - ./tsconfig.build.json:/workspace/tsconfig.build.json
      - ./tsconfig.jest.json:/workspace/tsconfig.jest.json
      - ./tsconfig.json:/workspace/tsconfig.json
  node18:
    build:
      context: .
      target: node18
    working_dir: /workspace
    entrypoint: /workspace/docker.entrypoint.sh
    volumes:
      - ./bin:/workspace/bin
      - ./docker.entrypoint.sh:/workspace/docker.entrypoint.sh
      - ./eslint.config.mjs:/workspace/eslint.config.mjs
      - ./gulpfile.js:/workspace/gulpfile.js
      - ./index-builder.js:/workspace/index-builder.js
      - ./jest.config.ts:/workspace/jest.config.ts
      - ./lint-staged.config.js:/workspace/lint-staged.config.js
      - ./package.json:/workspace/package.json
      - ./packer.js:/workspace/packer.js
      - ./prettierrc.json:/workspace/.prettierrc.json
      - ./rollup.config.js:/workspace/rollup.config.js
      - ./src:/workspace/src
      - ./test:/workspace/test
      - ./tmp/.deploy_git:/workspace/tmp/.deploy_git
      - ./tmp/docker-caches/node-18/dist:/workspace/dist
      - ./tmp/docker-caches/node-18/logs:/workspace/tmp/logs
      - ./tmp/docker-caches/node-18/tmp/jest:/workspace/tmp/jest
      - ./tmp/project-test:/workspace/tmp/project-test
      - ./tsconfig.base.json:/workspace/tsconfig.base.json
      - ./tsconfig.build.json:/workspace/tsconfig.build.json
      - ./tsconfig.jest.json:/workspace/tsconfig.jest.json
      - ./tsconfig.json:/workspace/tsconfig.json
  node20:
    build:
      context: .
      target: node20
    working_dir: /workspace
    entrypoint: /workspace/docker.entrypoint.sh
    volumes:
      - ./bin:/workspace/bin
      - ./docker.entrypoint.sh:/workspace/docker.entrypoint.sh
      - ./eslint.config.mjs:/workspace/eslint.config.mjs
      - ./gulpfile.js:/workspace/gulpfile.js
      - ./index-builder.js:/workspace/index-builder.js
      - ./jest.config.ts:/workspace/jest.config.ts
      - ./lint-staged.config.js:/workspace/lint-staged.config.js
      - ./package.json:/workspace/package.json
      - ./packer.js:/workspace/packer.js
      - ./prettierrc.json:/workspace/.prettierrc.json
      - ./rollup.config.js:/workspace/rollup.config.js
      - ./src:/workspace/src
      - ./test:/workspace/test
      - ./tmp/.deploy_git:/workspace/tmp/.deploy_git
      - ./tmp/docker-caches/node-20/dist:/workspace/dist
      - ./tmp/docker-caches/node-20/logs:/workspace/tmp/logs
      - ./tmp/docker-caches/node-20/tmp/jest:/workspace/tmp/jest
      - ./tmp/project-test:/workspace/tmp/project-test
      - ./tsconfig.base.json:/workspace/tsconfig.base.json
      - ./tsconfig.build.json:/workspace/tsconfig.build.json
      - ./tsconfig.jest.json:/workspace/tsconfig.jest.json
      - ./tsconfig.json:/workspace/tsconfig.json
  node22:
    build:
      context: .
      target: node22
    working_dir: /workspace
    entrypoint: /workspace/docker.entrypoint.sh
    volumes:
      - ./bin:/workspace/bin
      - ./docker.entrypoint.sh:/workspace/docker.entrypoint.sh
      - ./eslint.config.mjs:/workspace/eslint.config.mjs
      - ./gulpfile.js:/workspace/gulpfile.js
      - ./index-builder.js:/workspace/index-builder.js
      - ./jest.config.ts:/workspace/jest.config.ts
      - ./lint-staged.config.js:/workspace/lint-staged.config.js
      - ./package.json:/workspace/package.json
      - ./packer.js:/workspace/packer.js
      - ./prettierrc.json:/workspace/.prettierrc.json
      - ./rollup.config.js:/workspace/rollup.config.js
      - ./src:/workspace/src
      - ./test:/workspace/test
      - ./tmp/.deploy_git:/workspace/tmp/.deploy_git
      - ./tmp/docker-caches/node-22/dist:/workspace/dist
      - ./tmp/docker-caches/node-22/logs:/workspace/tmp/logs
      - ./tmp/docker-caches/node-22/tmp/jest:/workspace/tmp/jest
      - ./tmp/project-test:/workspace/tmp/project-test
      - ./tsconfig.base.json:/workspace/tsconfig.base.json
      - ./tsconfig.build.json:/workspace/tsconfig.build.json
      - ./tsconfig.jest.json:/workspace/tsconfig.jest.json
      - ./tsconfig.json:/workspace/tsconfig.json
