name: Build

on: [push, pull_request]

# run single job
concurrency:
  group: build-pre-release
  cancel-in-progress: true

jobs:
  build:
    env:
      NODE_OPTIONS: '--max_old_space_size=8192' #8192 4096 --expose-gc
      YARN_ENABLE_IMMUTABLE_INSTALLS: false
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN || secrets.GITHUB_TOKEN }}
      node_version: 14.x
      YARN_CHECKSUM_BEHAVIOR: update

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: initialize nodejs
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node_version }}

      - name: Enable corepack
        run: corepack enable

      - uses: actions/cache@v3
        id: cache
        with:
          path: |
            **/.yarn
            ./release
            ./yarn.lock
            ./releases/yarn.lock
            **/node_modules
            **/tmp
            **/dist
          key: ${{ runner.os }}-${{ env.node_version }}
          restore-keys: |
            ${{ runner.os }}-${{ env.node_version }}
            ${{ runner.os }}-

      - name: Install Global Packages
        run: npm i -g typescript ts-node gulp-cli hexo-cli webpack-cli

      - name: Install
        run: |
          yarn cache clean --all
          rm yarn.lock
          touch yarn.lock
          yarn install
        id: install
        shell: bash

      - name: Build
        run: npm run build
      - name: Pack
        run: npm run pack -- --commit
