name: Build

on: [push, pull_request, workflow_call, workflow_dispatch]

# run single job
concurrency:
  group: build-pre-release
  cancel-in-progress: true

jobs:
  build:
    env:
      NODE_OPTIONS: '--max_old_space_size=8192' #8192 4096 --expose-gc
      YARN_ENABLE_IMMUTABLE_INSTALLS: false
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      node_version: 14.x
      YARN_CHECKSUM_BEHAVIOR: update
      YARN_ENABLE_SCRIPTS: true
      YARN_NODE_LINKER: node-modules

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          submodule: recursive

      - name: Pull & update submodules recursively
        continue-on-error: true
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote
          git pull -X theirs
          echo "init submodules"
          git submodule init
          git submodule foreach "git submodule init"
          echo "sync submodules"
          git submodule sync
          git submodule foreach "git submodule sync"
          echo "update submodules"
          mkdir -p bin >/dev/null 2>&1
          curl -L https://github.com/dimaslanjaka/bin/raw/master/bin/submodule-install > bin/submodule-install
          rm -rf .git/modules
          bash ./bin/submodule-install

      - name: initialize nodejs
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node_version }}

      - name: Enable corepack
        run: corepack enable

      - uses: actions/cache@v3
        id: cache
        with:
          path: |
            **/.yarn
            ./release
            ./yarn.lock
            ./releases/yarn.lock
            **/node_modules
            **/tmp
            **/dist
          key: ${{ runner.os }}-${{ env.node_version }}
          restore-keys: |
            ${{ runner.os }}-${{ env.node_version }}
            ${{ runner.os }}-

      - name: Install Global Packages
        run: npm i -g typescript ts-node gulp-cli hexo-cli webpack-cli

      - name: Install
        run: touch yarn.lock && yarn install --inline-builds
        id: install
        shell: bash

      - name: Build
        run: npm run build
      - name: Pack
        run: npm run pack -- --commit
