name: Build

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
        default: 14.x
      os:
        required: false
        type: string
        default: ubuntu-latest
      repository:
        required: true
        type: string
      branch:
        required: true
        type: string
        default: master
      yarn-version:
        required: false
        type: string
        default: stable
    secrets:
      ACCESS_TOKEN:
        required: true
  workflow_dispatch:

jobs:
  build:
    name: "Builder | OS: ${{ inputs.os }} | Node: ${{ inputs.node-version }} | Yarn: ${{ inputs.yarn-version }}"
    env:
      NODE_OPTIONS: "--max_old_space_size=8192" #8192 4096 --expose-gc
      YARN_ENABLE_IMMUTABLE_INSTALLS: false
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN || secrets.GITHUB_TOKEN }}
      node-version: ${{ inputs.node-version }}
      YARN_CHECKSUM_BEHAVIOR: update
      YARN_ENABLE_SCRIPTS: true
      YARN_NODE_LINKER: node-modules
      YARN_IGNORE_NODE: ${{ contains('14.x,16.x', inputs.node-version) && '1' || '' }}

    runs-on: ${{ inputs.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN || secrets.GITHUB_TOKEN }}
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.branch }}

      - uses: actions/cache@v4
        name: save cache
        with:
          path: |
            **/.yarn
            **/release*
            **/yarn.lock
            **/node_modules
            **/tmp
            **/dist
          key: ${{ runner.os }}-${{ env.node-version }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}
            ${{ runner.os }}-

      - name: initialize Node ${{ env.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}

      - name: Enable corepack
        run: corepack enable

      - name: Pull & update submodules recursively
        continue-on-error: true
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote
          git pull -X theirs
          echo "init submodules"
          git submodule init
          git submodule foreach "git submodule init"
          echo "sync submodules"
          git submodule sync
          git submodule foreach "git submodule sync"
          echo "update submodules"
          mkdir -p bin >/dev/null 2>&1
          npm install -g rimraf binary-collections@https://raw.githubusercontent.com/dimaslanjaka/bin/master/releases/bin.tgz
          npx rimraf .git/modules
          npx submodule-install

      - name: Install Global Packages
        run: npm i -g typescript ts-node gulp-cli hexo-cli webpack-cli

      - name: Install
        id: install
        shell: bash
        run: |
          touch yarn.lock
          (
            curl -o .yarn/releases/yarn-${{ inputs.yarn-version }}.cjs https://repo.yarnpkg.com/${{ inputs.yarn-version }}/packages/yarnpkg-cli/bin/yarn.js \
            || curl -o .yarn/releases/yarn-${{ inputs.yarn-version }}.cjs https://raw.githubusercontent.com/yarnpkg/berry/%40yarnpkg/cli/${{ inputs.yarn-version }}/packages/yarnpkg-cli/bin/yarn.js
          )
          if grep -q '^yarnPath:' .yarnrc.yml 2>/dev/null; then
            sed -i.bak "s|^yarnPath:.*$|yarnPath: .yarn/releases/yarn-${{ inputs.yarn-version }}.cjs|" .yarnrc.yml
          else
            echo "yarnPath: .yarn/releases/yarn-${{ inputs.yarn-version }}.cjs" >> .yarnrc.yml
          fi
          yarn set version ${{ inputs.yarn-version }}
          yarn install

      - name: Build
        run: npm run build
      - name: Pack
        run: npm run pack
