name: Tester

on:
  push:
    paths:
      - "**/src/*.ts"
      - "**/test/*.ts"
      - "**/src/*.js"
      - "**/test/*.js"
      - "**/.github/workflows/tester.yml"
      - "**/.github/workflows/builder.yml"
      - "**/package.json"
      - "**/yarn.lock"
      - "**/package-lock.json"
  pull_request:
    types:
      - closed
    paths:
      - "**/src/*.ts"
      - "**/test/*.ts"
      - "**/src/*.js"
      - "**/test/*.js"
      - "**/package.json"
      - "**/yarn.lock"
      - "**/package-lock.json"
  workflow_dispatch:

concurrency:
  group: tester-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: ["18.x", "20.x", "22.x", "24.x"]
      fail-fast: false
    name: "Build ${{ matrix.os }} Node ${{ matrix.node-version }}"
    uses: ./.github/workflows/builder.yml
    with:
      node-version: ${{ matrix.node-version }}
      os: ${{ matrix.os }}
      repository: dimaslanjaka/git-command-helper
      branch: ${{ github.ref_name }}
    secrets:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN || secrets.GITHUB_TOKEN }}

  tester:
    needs: [build]
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: ["18.x", "20.x", "22.x", "24.x"]
      fail-fast: false
    env:
      NODE_OPTIONS: "--max_old_space_size=8192"
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN || secrets.GITHUB_TOKEN }}
      YARN_ENABLE_IMMUTABLE_INSTALLS: false
      YARN_CHECKSUM_BEHAVIOR: update
      YARN_ENABLE_SCRIPTS: true
      YARN_NODE_LINKER: node-modules
      YARN_IGNORE_NODE: 0

    runs-on: ${{ matrix.os }}

    name: "Test ${{ matrix.os }} Node ${{ matrix.node-version }}"
    steps:
      - name: ⬇️ Checkout
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.ACCESS_TOKEN || secrets.GITHUB_TOKEN }}

      - name: "⚙️ Setup Environment"
        uses: ./.github/actions/setup-environments
        id: setup-env
        with:
          node-version: ${{ matrix.node-version }}
          token: ${{ secrets.ACCESS_TOKEN || secrets.GITHUB_TOKEN }}
          prefix-cache-key: ${{ matrix.os }}-${{ matrix.node-version }}-

      - name: "📥 Install Dependencies"
        run: |
          if [ "${{ steps.setup-env.outputs.PACKAGE_MANAGER }}" == "npm" ]; then
            npm install --legacy-peer-deps || npm install --verbose || npm install --no-shrinkwrap --update-binary || npm install
          else
            touch yarn.lock
            yarn install --inline-builds || yarn install --verbose || yarn install --inline-builds || yarn install --inline-builds
          fi
        id: install
        shell: bash
        continue-on-error: true

      - name: "🔍 Diagnose Dependency Issues"
        if: failure() && steps.install.conclusion == 'failure'
        run: npx npm-check --skip-unused
        shell: bash

      - name: "🔨 Build"
        run: npm run build

      - name: "🧪 Run Tests"
        run: npm test

  coverage:
    needs: [tester]
    runs-on: ${{ matrix.os }}
    env:
      NODE_OPTIONS: "--max_old_space_size=8192"
      YARN_ENABLE_IMMUTABLE_INSTALLS: false
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN || secrets.GITHUB_TOKEN }}
      YARN_ENABLE_SCRIPTS: true
      YARN_NODE_LINKER: node-modules
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: ["18.x", "20.x", "22.x", "24.x"]
    steps:
      - name: ⬇️ Checkout
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.ACCESS_TOKEN || secrets.GITHUB_TOKEN }}

      - name: "⚙️ Setup Environment"
        uses: ./.github/actions/setup-environments
        with:
          node-version: ${{ matrix.node-version }}
          token: ${{ secrets.ACCESS_TOKEN || secrets.GITHUB_TOKEN }}
          prefix-cache-key: ${{ matrix.os }}-${{ matrix.node-version }}-

      - name: "⬇️ Checkout test-repo"
        uses: actions/checkout@v6
        with:
          repository: dimaslanjaka/test-repo
          path: tmp/project-test
          ref: test

      - name: "⬇️ Checkout dimaslanjaka.github.io"
        uses: actions/checkout@v6
        with:
          repository: dimaslanjaka/dimaslanjaka.github.io
          path: tmp/.deploy_git
          ref: master

      - name: "📥 Install Dependencies"
        run: npm install

      - name: "🔨 Build"
        run: npm run build

      - name: "📊 Coverage"
        run: npm run test-cov
        env:
          CI: true

      - name: "📤 Coveralls"
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.ACCESS_TOKEN || secrets.GITHUB_TOKEN }}
